<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24525" started-at="2020-04-08T22:00:46 PDT" finished-at="2020-04-08T22:01:11 PDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24525" started-at="2020-04-08T22:00:46 PDT" finished-at="2020-04-08T22:01:11 PDT">
      <class name="XeroAppTestCases">
        <test-method status="PASS" signature="intialize()[pri:0, instance:XeroAppTestCases@67205a84]" name="intialize" is-config="true" duration-ms="1932" started-at="2020-04-08T22:00:46 PDT" finished-at="2020-04-08T22:00:48 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method status="PASS" signature="NavigateToXero()[pri:0, instance:XeroAppTestCases@67205a84]" name="NavigateToXero" duration-ms="7715" started-at="2020-04-08T22:00:48 PDT" finished-at="2020-04-08T22:00:56 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToXero -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:XeroAppTestCases@67205a84]" name="closeBrowser" is-config="true" duration-ms="302" started-at="2020-04-08T22:00:56 PDT" finished-at="2020-04-08T22:00:56 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="intialize()[pri:0, instance:XeroAppTestCases@67205a84]" name="intialize" is-config="true" duration-ms="1292" started-at="2020-04-08T22:00:56 PDT" finished-at="2020-04-08T22:00:58 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method status="FAIL" signature="forgotPassword()[pri:0, instance:XeroAppTestCases@67205a84]" name="forgotPassword" duration-ms="2341" started-at="2020-04-08T22:00:58 PDT" finished-at="2020-04-08T22:01:00 PDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Link to rest Message is not displayed expected [A link to reset your password has been sent to: testQA20mar@gmail.com] but found [A link to reset your password has been sent to:
testQA2020mar@gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Link to rest Message is not displayed expected [A link to reset your password has been sent to: testQA20mar@gmail.com] but found [A link to reset your password has been sent to:
testQA2020mar@gmail.com]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at XeroAppTestCases.forgotPassword(XeroAppTestCases.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPassword -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:XeroAppTestCases@67205a84]" name="closeBrowser" is-config="true" duration-ms="150" started-at="2020-04-08T22:01:00 PDT" finished-at="2020-04-08T22:01:00 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="intialize()[pri:0, instance:XeroAppTestCases@67205a84]" name="intialize" is-config="true" duration-ms="987" started-at="2020-04-08T22:01:00 PDT" finished-at="2020-04-08T22:01:01 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method status="FAIL" signature="incorrectEmail()[pri:0, instance:XeroAppTestCases@67205a84]" name="incorrectEmail" duration-ms="3228" started-at="2020-04-08T22:01:01 PDT" finished-at="2020-04-08T22:01:04 PDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message not displayed expected [Your email or password is incorrect] but found [Your account has been temporarily locked. Please try again in 15 minutes or reset your password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message not displayed expected [Your email or password is incorrect] but found [Your account has been temporarily locked. Please try again in 15 minutes or reset your password.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at XeroAppTestCases.incorrectEmail(XeroAppTestCases.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmail -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:XeroAppTestCases@67205a84]" name="closeBrowser" is-config="true" duration-ms="151" started-at="2020-04-08T22:01:04 PDT" finished-at="2020-04-08T22:01:04 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="intialize()[pri:0, instance:XeroAppTestCases@67205a84]" name="intialize" is-config="true" duration-ms="1066" started-at="2020-04-08T22:01:04 PDT" finished-at="2020-04-08T22:01:05 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method status="PASS" signature="incorrectPassword()[pri:0, instance:XeroAppTestCases@67205a84]" name="incorrectPassword" duration-ms="5133" started-at="2020-04-08T22:01:05 PDT" finished-at="2020-04-08T22:01:11 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectPassword -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:XeroAppTestCases@67205a84]" name="closeBrowser" is-config="true" duration-ms="167" started-at="2020-04-08T22:01:11 PDT" finished-at="2020-04-08T22:01:11 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- XeroAppTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
